<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\AIMonitor.Domain\AIMonitor.Domain.csproj" />
    <ProjectReference Include="..\..\src\AIMonitor.Application\AIMonitor.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
